const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
const SAVE_TODO_SUCCESS = 'SAVE_TODO_SUCCESS'
const FETCH_TODO_FAILED = 'FETCH_TODO_FAILED'
const SAVE_TODO_FAILED = 'SAVE_TODO_FAILED'
const FETCH_TODO_LOADING = 'FETCH_TODO_LOADING'
const SAVE_TODO_LOADING = 'SAVE_TODO_LOADING'

export {
  FETCH_TODO_SUCCESS,
  SAVE_TODO_SUCCESS,
  FETCH_TODO_FAILED,
  SAVE_TODO_FAILED,
  FETCH_TODO_LOADING,
  SAVE_TODO_LOADING
}