const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
const FETCH_TODO_FAILED = 'FETCH_TODO_FAILED'
const FETCH_TODO_LOADING = 'FETCH_TODO_LOADING'

const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
const ADD_TODO_FAILED = 'ADD_TODO_FAILED'
const ADD_TODO_LOADING = 'ADD_TODO_LOADING'

const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
const UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED'
const UPDATE_TODO_LOADING = 'UPDATE_TODO_LOADING'


export {
  FETCH_TODO_SUCCESS,
  FETCH_TODO_LOADING,
  FETCH_TODO_FAILED,
  ADD_TODO_SUCCESS,
  ADD_TODO_LOADING,
  ADD_TODO_FAILED,
  UPDATE_TODO_SUCCESS,
  UPDATE_TODO_FAILED,
  UPDATE_TODO_LOADING
}